# YOLO Mob Finder Configuration
# Adjust these settings for optimal performance

# Model Settings
model:
  path: "yolov8n.pt"              # Model path (yolov8n.pt for speed, your custom model for accuracy)
  confidence_threshold: 0.25       # Detection confidence threshold (0.1-0.9)
  iou_threshold: 0.45             # IoU threshold for non-max suppression
  max_detections: 300             # Maximum detections per frame

# Performance Settings
performance:
  target_fps: 30                  # Target FPS for real-time processing
  use_gpu: true                   # Use GPU if available (much faster)
  use_half_precision: true        # Use FP16 for speed boost (GPU only)

# Screen Area Settings
screen:
  width: 1920
  height: 1080
  margins:
    top: 100                      # Pixels to ignore at top (UI elements)
    bottom: 200                   # Pixels to ignore at bottom (chat, UI)
    left: 100                     # Pixels to ignore at left
    right: 100                    # Pixels to ignore at right

# Protection Settings
protection:
  character_radius: 150           # Protection radius around screen center (pixels)
  enable_name_protection: false   # Future: protect by character/pet names
  
# Targeting Settings
targeting:
  offset_y: 10                   # Vertical offset for clicking (pixels below detection center)
  prefer_closest: true           # Target closest mob to character
  click_delay: 0.1               # Delay between clicks (seconds)

# Keyboard Automation
keyboard:
  enabled: true                  # Enable keyboard automation
  sequence: "123145"             # Key sequence to press
  sequence_delay: 1.0            # Delay between full sequences (seconds)
  key_delay: 0.1                 # Delay between individual keys (seconds)

# Logging and Debug
logging:
  show_fps: true                 # Show FPS counter
  show_detections: true          # Print detection information
  fps_update_interval: 30        # Update FPS display every N frames
  verbose: false                 # Detailed logging (impacts performance)

# Advanced YOLO Settings (for experts)
yolo_advanced:
  augment: false                 # Test-time augmentation (slower but more accurate)
  agnostic_nms: false           # Class-agnostic non-max suppression
  multi_label: false            # Multiple labels per box
  classes: null                 # Filter by class (null = all classes)
